Introduced security to the project
VolodymyrSkvira/online-book-store pull request #6
Opened 2023-10-27 15:28 UTC by VolodymyrSkvira

2023-10-27 17:38 UTC, RedArtelerist requested changes
Good job, let's improve your solution

2023-10-27 17:38 UTC, RedArtelerist commented on src/main/java/s/volodymyr/onlinebookstore/config/Encrypter.java
> +}
Can we move it to SecurityConfig?

2023-10-27 17:38 UTC, RedArtelerist commented on src/main/java/s/volodymyr/onlinebookstore/controller/AuthenticationController.java
> +    )
Add some details to description

2023-10-27 17:38 UTC, RedArtelerist commented on src/main/java/s/volodymyr/onlinebookstore/controller/AuthenticationController.java
> +            throws RegistrationException {
I don't see where you handle RegistrationException. I think it's the same with AutrnticationException

2023-10-27 17:38 UTC, RedArtelerist commented on src/main/java/s/volodymyr/onlinebookstore/controller/BookController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
You can use just "hasRole('ADMIN')". The same in other places

2023-10-27 17:38 UTC, RedArtelerist commented on src/main/java/s/volodymyr/onlinebookstore/dto/user/UserLoginRequestDto.java
> +        String email,
Add Email annotation to this field

2023-10-27 17:38 UTC, RedArtelerist commented on src/main/java/s/volodymyr/onlinebookstore/dto/user/UserRegistrationRequestDto.java
> +        String email,
Email annotation

2023-10-27 17:38 UTC, RedArtelerist commented on src/main/java/s/volodymyr/onlinebookstore/dto/user/UserRegistrationRequestDto.java
> +        String password,
Maybe add some pattern that passwords have to consist only of letters and numbers or something like that. But it's up to you

2023-10-27 17:38 UTC, RedArtelerist commented on src/main/java/s/volodymyr/onlinebookstore/dto/user/UserRegistrationRequestDto.java
> +public record UserRegistrationRequestDto(
I don't see where your passwords matching validation)

2023-10-27 17:38 UTC, RedArtelerist commented on src/main/java/s/volodymyr/onlinebookstore/mapper/UserMapper.java
> +        implementationPackage = "<PACKAGE_NAME>.impl"
You can omit this line. Spring uses in by default.

2023-10-27 17:38 UTC, RedArtelerist commented on src/main/java/s/volodymyr/onlinebookstore/model/Role.java
> +    @Column(name = "is_deleted")
```suggestion
    @Column(name = "is_deleted", nullable=false)
```

2023-10-27 17:38 UTC, RedArtelerist commented on src/main/java/s/volodymyr/onlinebookstore/model/User.java
> +    private Set<Role> roles;
Do we really need in this place FetchType.EAGER, I don't sure. But ok

2023-10-27 17:38 UTC, RedArtelerist commented on src/main/java/s/volodymyr/onlinebookstore/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
Magic literals, add this Authorization as a constant.

2023-10-27 17:38 UTC, RedArtelerist commented on src/main/resources/application.properties
> +jwt.secret=IAmASecretIAmASecretIAmASecretIAmASecretIAmASecretIAmASecret
🙃

2023-10-30 08:31 UTC, VolodymyrSkvira commented on src/main/java/s/volodymyr/onlinebookstore/controller/AuthenticationController.java
> +            throws RegistrationException {
This exception will be handled by GlobalExceptionHandler

2023-10-30 08:32 UTC, VolodymyrSkvira commented on src/main/java/s/volodymyr/onlinebookstore/controller/AuthenticationController.java
> +    )
Enough is enough :) I`m not a book writer

2023-10-30 08:34 UTC, VolodymyrSkvira commented on src/main/java/s/volodymyr/onlinebookstore/mapper/UserMapper.java
> +        implementationPackage = "<PACKAGE_NAME>.impl"
I`ll just leave it here for now, just in case :)

2023-10-30 08:37 UTC, VolodymyrSkvira commented on src/main/java/s/volodymyr/onlinebookstore/model/User.java
> +    private Set<Role> roles;
U`re right, forgot to remove it while fixing something, thanks!

2023-10-30 10:51 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2023-10-30 10:51 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/controller/BookController.java
> +    @PreAuthorize("hasRole('ADMIN')")
Do we need to add ROLE_USER for some endpoints?

2023-10-30 10:51 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/dto/user/UserLoginRequestDto.java
> +
remove empty line

2023-10-30 10:51 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/dto/user/UserRegistrationRequestDto.java
> +
remove empty line

2023-10-30 10:51 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/dto/user/UserRegistrationRequestDto.java
> +        String shippingAddress
NotBlank ?

2023-10-30 10:51 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/mapper/UserMapper.java
> +    UserDto toDto(User user);
```suggestion
    UserDto toUserDto(User user);
```

2023-10-30 10:51 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/mapper/UserMapper.java
> +    UserResponseDto toResponseDto(User user);
```suggestion
    UserResponseDto toUserResponseDto(User user);
```

2023-10-30 10:51 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/security/AuthenticationService.java
> +
remove empty line

2023-10-30 10:51 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/security/AuthenticationService.java
> +
the same

2023-10-30 10:51 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/security/JwtAuthenticationFilter.java
> +    private static final String AUTHORIZATION_HEADER = "Authorization";
there is an existing constant: org.springframework.http.HttpHeaders.AUTHORIZATION

2023-10-30 10:51 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/UserServiceImpl.java
> +        Set<Role> roles = new HashSet<>();
It's good practice to declare variable in place where you are going to use it 

```suggestion
        User user = userMapper.toUser(request);
        user.setPassword(passwordEncoder.encode(user.getPassword()));
        Set<Role> roles = new HashSet<>();
        roles.add(roleRepository.findByName(RoleName.ROLE_USER));
        user.setRoles(roles);
```

2023-10-30 10:51 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/validation/FieldMatcherValidator.java
> +        if (password != null) {
```suggestion
       return password != null && password.equals(repeatPassword);
```

2023-10-30 11:59 UTC, VolodymyrSkvira commented on src/main/java/s/volodymyr/onlinebookstore/dto/user/UserRegistrationRequestDto.java
> +        String shippingAddress
I think there was no mention that shipping address is an obligatory field

2023-10-30 12:06 UTC, VolodymyrSkvira commented on src/main/java/s/volodymyr/onlinebookstore/controller/BookController.java
> +    @PreAuthorize("hasRole('ADMIN')")
Personally I don`t think that BookController should remain as it is, because usually users are able to search for something without registering on the website

2023-10-30 16:25 UTC, liliia-ponomarenko requested changes
Good job! Let’s fix a few mistakes;)

2023-10-30 16:25 UTC, liliia-ponomarenko commented on src/main/java/s/volodymyr/onlinebookstore/dto/user/UserLoginRequestDto.java
> +
not fixed

2023-10-30 16:25 UTC, liliia-ponomarenko commented on src/main/java/s/volodymyr/onlinebookstore/dto/user/UserDto.java
> +public record UserDto(
Do you use this Dto and toUserDto mapper? Let’s  remove redundant code

2023-10-30 16:25 UTC, liliia-ponomarenko commented on src/main/java/s/volodymyr/onlinebookstore/exception/RegistrationException.java
> +public class RegistrationException extends Exception {
Should you handle this exception in CustomGlobalExceptionHandler?

2023-10-30 16:25 UTC, liliia-ponomarenko commented on src/main/java/s/volodymyr/onlinebookstore/mapper/UserMapper.java
> +    UserDto toUserDto(User user);
you never used this method

2023-10-30 16:25 UTC, liliia-ponomarenko commented on src/main/java/s/volodymyr/onlinebookstore/model/User.java
> +    private String shippingAddress;
```suggestion
    @Column(name = "last_name", nullable = false)
    private String lastName;
    
    @Column(name = "shipping_address")
    private String shippingAddress;
```

2023-10-30 16:25 UTC, liliia-ponomarenko commented on src/main/java/s/volodymyr/onlinebookstore/repository/role/RoleRepository.java
> +public interface RoleRepository extends JpaRepository<Role, Long> {
Repository annotation is missing

2023-10-30 16:25 UTC, liliia-ponomarenko commented on src/main/java/s/volodymyr/onlinebookstore/repository/user/UserRepository.java
> +    Optional<User> findByEmail(String email);
Repository annotation is missing

2023-10-30 16:25 UTC, liliia-ponomarenko commented on src/main/java/s/volodymyr/onlinebookstore/security/CustomUserDetailsService.java
> +                .orElseThrow(() -> new RuntimeException("Can`t find user by email"));
better use   UsernameNotFoundException and remove it from signature

2023-10-30 16:25 UTC, liliia-ponomarenko commented on src/main/java/s/volodymyr/onlinebookstore/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
```suggestion
            return bearerToken.substring(BEARER_CODING.length());
```

2023-10-30 16:25 UTC, liliia-ponomarenko commented on src/main/java/s/volodymyr/onlinebookstore/service/UserService.java
> +    UserResponseDto register(UserRegistrationRequestDto request) throws RegistrationException;
why do you need throws here?

will the caller have to handle the exception?

2023-10-30 16:25 UTC, liliia-ponomarenko commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/UserServiceImpl.java
> +        if (userRepository.findByEmail(request.email()).isPresent()) {
you can use existsByEmail from repository

2023-10-30 16:25 UTC, liliia-ponomarenko commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/UserServiceImpl.java
> +
```suggestion
```

2023-10-30 16:25 UTC, liliia-ponomarenko commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/UserServiceImpl.java
> +        roles.add(roleRepository.findByName(RoleName.ROLE_USER));
you can use method of Set.of(defaultRole)

2023-10-30 16:25 UTC, liliia-ponomarenko commented on src/main/resources/application.properties
> +jwt.secret=IAmASecretIAmASecretIAmASecretIAmASecretIAmASecretIAmASecret
It’s funny) but it’s a project for your CV so better use a more secure `jwt.secret`

2023-10-30 16:25 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/02-create-roles-table.yaml
> +                    nullable: false
better end each file with one empty line

2023-10-30 16:25 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/03-create-users-table.yaml
> +                  type: varchar(255)
you should have the same max size in the request to because it occurs to SQL exception (check it everywhere)

2023-10-30 16:38 UTC, liliia-ponomarenko commented on src/main/java/s/volodymyr/onlinebookstore/security/CustomUserDetailsService.java
> +@Component
Service

2023-10-31 08:16 UTC, VolodymyrSkvira commented on src/main/java/s/volodymyr/onlinebookstore/controller/AuthenticationController.java
> +            throws RegistrationException {
> no need to declare throws on REST layer

This is the requirement from the hw

2023-10-31 08:18 UTC, VolodymyrSkvira commented on src/main/java/s/volodymyr/onlinebookstore/controller/BookController.java
> +    @PreAuthorize("hasRole('ADMIN')")
Got it, will adjust access for users

2023-10-31 08:32 UTC, VolodymyrSkvira commented on src/main/java/s/volodymyr/onlinebookstore/exception/RegistrationException.java
> +public class RegistrationException extends Exception {
Agree

2023-10-31 08:39 UTC, VolodymyrSkvira commented on src/main/java/s/volodymyr/onlinebookstore/service/UserService.java
> +    UserResponseDto register(UserRegistrationRequestDto request) throws RegistrationException;
This is the way it was in the video, not sure if I should change anything here

2023-10-31 08:46 UTC, VolodymyrSkvira commented on src/main/resources/db/changelog/changes/03-create-users-table.yaml
> +                  type: varchar(255)
I checked and haven`t found any size that differs

2023-10-31 10:43 UTC, Elena-Bruyako requested changes
Good work! Need to fix several comments

2023-10-31 10:43 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +                .status(HttpStatus.BAD_REQUEST)
you should use 409 CONFLICT

2023-10-31 10:43 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/security/CustomUserDetailsService.java
> +@Component
Not fixed

2023-10-31 10:43 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/03-create-users-table.yaml
> +                  type: varchar(255)
Check email and password sizes

2023-10-31 16:56 UTC, liliia-ponomarenko approved these changes
Good job! 👍

2023-10-31 16:57 UTC, liliia-ponomarenko commented on src/main/java/s/volodymyr/onlinebookstore/security/CustomUserDetailsService.java
> +@Component
```suggestion
```

2023-10-31 17:14 UTC, merged