Implemented Category entity and all additional classes
VolodymyrSkvira/online-book-store pull request #7
Opened 2023-10-31 13:11 UTC by VolodymyrSkvira

2023-10-31 21:56 UTC, don-bigdad approved these changes

2023-10-31 21:56 UTC, don-bigdad commented on src/main/java/s/volodymyr/onlinebookstore/repository/category/CategoryRepository.java
> +    Optional<Category> getCategoryById(Long id);
You really need to write it?

2023-11-02 09:08 UTC, liliia-ponomarenko requested changes
Good job! Let’s fix a few mistakes;)

2023-11-02 09:08 UTC, liliia-ponomarenko commented on src/main/java/s/volodymyr/onlinebookstore/repository/category/CategoryRepository.java
> +    Optional<Category> getCategoryById(Long id);
agree

2023-11-02 09:08 UTC, liliia-ponomarenko commented on src/main/java/s/volodymyr/onlinebookstore/service/CategoryService.java
> +    CreateCategoryRequestDto update(Long id, CategoryDto categoryDto);
you should pass CreateCategoryRequestDto and return CategoryDto

2023-11-02 09:08 UTC, liliia-ponomarenko commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.save(bookMapper.toBook(bookRequestDto)));
Can you create a book with categories?

2023-11-02 09:08 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/06-create-categories-table.yaml
> +                    nullable: false
Let’s  add one empty line at the end (check other files)

2023-11-04 13:20 UTC, NazarSmith228 requested changes
Good job! Let's improve your solution

2023-11-04 13:20 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/controller/BookController.java
>      @ResponseStatus(HttpStatus.OK)
just FYI

`OK` is the default response status, so you can omit it

remember about this in future :)

2023-11-04 13:20 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/controller/BookController.java
> +               description = "Receive a list of available books")
what is the point of this change?


and all other changes in this class...

2023-11-04 13:20 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/controller/CategoryController.java
> +    @PreAuthorize("hasAnyRole('USER','ADMIN')")
shouldn't admin user also have a role `USER`?

or you design your app in a way that admin does not have same priviliges as user has?

2023-11-04 13:20 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/controller/CategoryController.java
> +            @PageableDefault(size = 5) Pageable pageable) {
```suggestion
    public List<CategoryDto> getAll(@PageableDefault(size = 5) Pageable pageable) {
```

2023-11-04 13:20 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/controller/CategoryController.java
> +    public CategoryDto getCategoryById(@PathVariable @Positive Long id) {
`@Positive` will not work since you haven't annotated your controller with `@Validated`

2023-11-04 13:20 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/controller/CategoryController.java
> +    ) {
```suggestion
    public List<BookDtoWithoutCategoryIds> getBooksByCategoryId(@PathVariable @Positive Long id,
                                                                @PageableDefault(size = 5) Pageable pageable) {
```

2023-11-04 13:20 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/dto/book/CreateBookRequestDto.java
> +        List<Long> categoryIds
you may also validate this
```suggestion
        @NotEmpty List<@Positive Long> categoryIds
```

2023-11-04 13:20 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.save(bookMapper.toBook(bookRequestDto)));
@VolodymyrSkvira  you haven't answered the question here :)

2023-11-04 13:20 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/CategoryServiceImpl.java
> +        ));
can be simplified:
```
return repo.findById(id).map(mapper::toDto).orElseThrow(...);
```

2023-11-04 13:20 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/CategoryServiceImpl.java
> +        categoryRepository.deleteById(id);
what if there is no category with such id?

2023-11-04 13:20 UTC, NazarSmith228 commented on src/main/resources/db/changelog/changes/03-create-users-table.yaml
> +                  type: varchar(60)
please avoid updating existing migrations

this is ok for local setup (don't forget to clear Liquibase table), however don't get used to it :)

2023-11-04 22:41 UTC, VolodymyrSkvira commented on src/main/java/s/volodymyr/onlinebookstore/controller/BookController.java
> +               description = "Receive a list of available books")
Just a cosmetic change, that`s all :)

2023-11-04 22:47 UTC, VolodymyrSkvira commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.save(bookMapper.toBook(bookRequestDto)));
@NazarSmith228 Yes, I didn't reply, just decided to implement it :)

2023-11-04 22:53 UTC, VolodymyrSkvira commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/CategoryServiceImpl.java
> +        categoryRepository.deleteById(id);
Here's direct quote from this method's documentation: 
"Deletes the entity with the given id.
If the entity is not found in the persistence store it is silently ignored.
Params:
id – must not be null.
Throws:
IllegalArgumentException – in case the given id is null"

2023-11-04 22:55 UTC, VolodymyrSkvira commented on src/main/resources/db/changelog/changes/03-create-users-table.yaml
> +                  type: varchar(60)
Got it, just needed to change it so the project would work

2023-11-05 10:51 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/controller/BookController.java
> +               description = "Receive a list of available books")
@VolodymyrSkvira pls avoid such cosmetic changes in scope of your PRs :)

2023-11-05 10:51 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/CategoryServiceImpl.java
> +        categoryRepository.deleteById(id);
@VolodymyrSkvira yup, you're right

2023-11-05 10:58 UTC, NazarSmith228 approved these changes
LGTM, but please, address all my minor remarks

2023-11-05 10:58 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/controller/CategoryController.java
> +    @PreAuthorize("hasAnyRole('USER')")
```suggestion
    @PreAuthorize("hasRole('USER')")
```

2023-11-05 10:58 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/controller/CategoryController.java
> +    @PreAuthorize("hasAnyRole('USER')")
```suggestion
    @PreAuthorize("hasRole('USER')")
```

2023-11-05 10:58 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/dto/book/BookDtoWithoutCategoryIds.java
> +) {
```suggestion
        String coverImage) {
```

2023-11-05 10:58 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/dto/book/CreateBookRequestDto.java
>  ) {
```suggestion
        List<@Positive Long> categoryIds) {
```

2023-11-05 10:58 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/dto/category/CategoryDto.java
> +) {
```suggestion
        String description) {
```

2023-11-05 10:58 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/dto/category/CreateCategoryRequestDto.java
> +) {
```suggestion
        String description) {
```

2023-11-05 10:58 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/dto/user/UserLoginRequestDto.java
>  ) {
```suggestion
        String password) {
```

2023-11-05 10:58 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/CategoryServiceImpl.java
> +                .toDto(categoryRepository.save(categoryMapper.toCategory(categoryRequest)));
it may be beneficial for readability to create at least 1 intermediate variable here :)

2023-11-05 12:56 UTC, merged