Implemented ShoppingCart and CartItem entities
VolodymyrSkvira/online-book-store pull request #8
Opened 2023-11-07 10:20 UTC by VolodymyrSkvira

2023-11-10 06:32 UTC, NazarSmith228 requested changes
Good job! Let's improve your solution

2023-11-10 06:32 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/controller/ShoppingCartController.java
> +@Validated
this annotation is redundant, since you don't validate path variable

either start validating it or remove the annotation

2023-11-10 06:32 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/dto/cartitem/CreateCartItemRequestDto.java
> +        int quantity) {
what makes you use `@Positive` for bookId and `@Min(1)` for quantity?

why not using `@Positive` for both?

2023-11-10 06:32 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/model/CartItem.java
> +    @ManyToOne(fetch = FetchType.LAZY)
pls add `optional = false` since cart item can't exist without shopping cart

2023-11-10 06:32 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/model/CartItem.java
> +    @ManyToOne(fetch = FetchType.LAZY)
pls add `optional = false` since cart item can't exist without book

2023-11-10 06:32 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/model/ShoppingCart.java
> +    @OneToMany(mappedBy = "shoppingCart")
makes sense to add `cascade = CascadeType.ALL` and `orphanRemoval = true`, since cart item lifecycle is bound to shopping cart

2023-11-10 06:32 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/model/ShoppingCart.java
> +    @OneToOne
1. avoid `EAGER` fetch type
2. add `optional = false` since shopping cart can't exist without user
3. think of bidirectional mapping - as of now the mapping is unidirectional, meaning that you don't have any reference to ShoppingCart on User side. what will happen if you delete User?

2023-11-10 06:32 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +    @Transactional
makes sense to add `readOnly = true`, since you don't make any changes to the DB here

2023-11-10 06:32 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/model/ShoppingCart.java
> +    private Set<CartItem> cartItems;
```suggestion
    private Set<CartItem> cartItems = new HashSet<>();
```

2023-11-10 06:32 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +                () -> {
complex lambdas are usually extracted to separate methods
```
orElseGet(() -> createShoppingCartForUser(user))
```

2023-11-10 06:32 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +    public ShoppingCartDto addToCart(Long id, CreateCartItemRequestDto requestDto) {
pls specify that this id belongs to user to avoid confusion
```suggestion
    public ShoppingCartDto addToCart(Long userId, CreateCartItemRequestDto requestDto) {
```

makes sense to adjust in all places

2023-11-10 06:32 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +                    newShoppingCart.setCartItems(new HashSet<>());
this initialization of set is redundant - it should be done automatically

2023-11-11 12:07 UTC, VolodymyrSkvira commented on src/main/java/s/volodymyr/onlinebookstore/controller/ShoppingCartController.java
> +@Validated
Right, I`ll just add the validation

2023-11-11 12:08 UTC, VolodymyrSkvira commented on src/main/java/s/volodymyr/onlinebookstore/dto/cartitem/CreateCartItemRequestDto.java
> +        int quantity) {
Good point

2023-11-13 10:12 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2023-11-13 10:12 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/controller/ShoppingCartController.java
> +                                          @RequestBody ChangeShoppingCartQuantityDto quantityDto) {
```suggestion
                                          @RequestBody @Valid ChangeShoppingCartQuantityDto quantityDto) {
```

2023-11-13 10:12 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/controller/ShoppingCartController.java
> +                                         @RequestBody CreateCartItemRequestDto requestDto) {
```suggestion
                                         @RequestBody @Valid CreateCartItemRequestDto requestDto) {
```

2023-11-13 10:12 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/dto/shoppingcart/ChangeShoppingCartQuantityDto.java
> +public record ChangeShoppingCartQuantityDto(
```suggestion
public record UpdateCartItemRequestDto(
```

2023-11-13 10:12 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/dto/shoppingcart/ChangeShoppingCartQuantityDto.java
> +        int quantity) {
`@Positive `?

2023-11-13 10:12 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +                () -> new RuntimeException("Cannot find shopping cart")
RuntimeException is too general. Use custom exception

2023-11-13 14:34 UTC, liliia-ponomarenko approved these changes
Good job!

2023-11-13 15:40 UTC, merged