Implemented Order and OrderItem entities
VolodymyrSkvira/online-book-store pull request #9
Opened 2023-11-08 16:28 UTC by VolodymyrSkvira

2023-11-10 16:42 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/controller/OrderController.java
> +@Validated
this annotation is redundant - you don't validate any request parameters

2023-11-10 16:43 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/model/Order.java
> +    @ManyToOne
pls set fetch type to lazy

also add `optional  = false` since order can't exist without user

2023-11-10 16:43 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/model/Order.java
> +    @OneToMany(mappedBy = "order", cascade = CascadeType.PERSIST)
I would use `ALL` cascade

also think about `orphanRemoval`

2023-11-10 16:44 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/model/OrderItem.java
> +    @ManyToOne(fetch = FetchType.LAZY)
pls add `optional = false`

2023-11-10 16:44 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/model/OrderItem.java
> +    @ManyToOne(fetch = FetchType.LAZY)
pls add `optional = false`

2023-11-10 16:45 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/OrderServiceImpl.java
> +    public List<OrderDto> getAllById(Pageable pageable, Long id) {
you have 3 GET methods - only 1 with `@Transactional` 

why ? :)

if you wish to use transactions in read method as well - consider annotating your service with 

`@Transactional(readOnly = true)`:
```
@Transactional(readOnly = true)
Service {

getMethod() {...}

@Transactional // to override read-only
updateMethod(){...}
}
```

2023-11-10 16:47 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/model/OrderItem.java
> +    private Book book;
pls make sure that when you delete a book order/cart items are deleted as well

2023-11-10 16:47 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/OrderServiceImpl.java
> +        orderRepository.save(order);
this method is transaction - you don't need to call save

2023-11-10 16:47 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/OrderServiceImpl.java
> +            orderItem.setOrder(order);
this seem to be a job for mapper

2023-11-10 16:48 UTC, NazarSmith228 commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/OrderServiceImpl.java
> +    private Order createOrderObject(Set<CartItem> cartItems) {
```suggestion
    private Order createOrderFrom(Set<CartItem> cartItems) {
```

2023-11-11 13:07 UTC, VolodymyrSkvira commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/OrderServiceImpl.java
> +    public List<OrderDto> getAllById(Pageable pageable, Long id) {
Right, removed @Transactional and added @EntityGraph in mapper

2023-11-11 13:43 UTC, VolodymyrSkvira commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/OrderServiceImpl.java
> +    private Order createOrderObject(Set<CartItem> cartItems) {
Deleted this method and changed logic a bit

2023-11-13 11:14 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2023-11-13 11:14 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/controller/OrderController.java
> +    public OrderDto updateOrder(@RequestBody UpdateOrderStatusDto updateDto,
```suggestion
    public OrderDto updateOrder(@RequestBody @Valid UpdateOrderStatusDto updateDto,
```

2023-11-13 11:14 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/controller/OrderController.java
> +                               @RequestBody CreateOrderRequestDto requestDto) {
```suggestion
                               @RequestBody @Valid CreateOrderRequestDto requestDto) {
```

2023-11-13 11:14 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/controller/OrderController.java
> +                                    Pageable pageable) {
Do you need pageable default?

2023-11-13 11:14 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/controller/OrderController.java
> +    public List<OrderItemDto> getItemsByOrderId(Pageable pageable,
The same

2023-11-13 11:14 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/dto/order/CreateOrderRequestDto.java
> +        String shippingAddress) {
Do we need some validation here?

2023-11-13 11:14 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/dto/order/UpdateOrderStatusDto.java
> +        Status status
The same about validation

2023-11-13 11:14 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/OrderServiceImpl.java
> +        order.setStatus(updateDto.status());
Did you check this logic? 
Maybe we need updateDto.status().name()?

2023-11-13 11:14 UTC, Elena-Bruyako commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/OrderServiceImpl.java
> +
remove empty line

2023-11-13 14:13 UTC, VolodymyrSkvira commented on src/main/java/s/volodymyr/onlinebookstore/service/impl/OrderServiceImpl.java
> +        order.setStatus(updateDto.status());
I can`t use it here 'cause setStatus() accepts only Status enum, but not string

2023-11-14 15:31 UTC, Elena-Bruyako commented on pom.xml
> +            <artifactId>spring-boot-docker-compose</artifactId>
This dependency is not related to this PR

2023-11-17 14:14 UTC, merged